[build]
  publish = "/"
  command = "" # No build command needed for static HTML/CSS/JS site

# Form handling settings
[build.processing.html]
  pretty_urls = true

# Redirect and rewrite rules
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Form success handling
[[redirects]]
  from = "/success"
  to = "/index.html#contact"
  status = 302

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer-when-downgrade"
    Content-Security-Policy = "default-src 'self' https://images.unsplash.com; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' https://images.unsplash.com; font-src 'self';"

# Enable Netlify form detection
[build.processing]
  skip_processing = false